### ISSUE TITLE
Triggerbot sometimes doesnt work

### ISSUE THREAD

**Issue by justasbeast** [AStupidRat/RatPoison#15] opened 2019-05-05 11:05 UTC
Triggerbot not always reacts to enemies

**Comment by JeeyM** [comment] 2019-05-05 11:29
I agree, I have the same problem, triggerbot doesn't work

**Comment by AStupidRat** [comment] 2019-05-05 12:22
@justasbeast @JeeyM Triggerbot relies on bSpotted to know if the enemy is in LoS, if you use Show Target (Enemy highlights yellow when inside aim fov) triggerbot should react to the enemy normally if the target is yellow and bones 3 through 7 (torso/chest bones) or bone 8 (head bone) is inside the bone trigger fov. Let me know if this is not the case and it isn't reacting when it should.

**Comment by JeeyM** [comment] 2019-05-05 12:38
Still doesn't work

**Comment by AStupidRat** [comment] 2019-05-06 07:04
@JeeyM Does it not work at all? Or just has times where it should shoot but doesnt? Latest version 1.2.6 is working fine for me.

**Comment by JeeyM** [comment] 2019-05-06 07:06
@AsStupidRat nope, for me is not working, or it's because I put both force aim key and triggerbot on alt?

**Comment by AStupidRat** [comment] 2019-05-06 11:10
@JeeyM As long as bone trigger is enabled it should be working fine, I tested by having force aim and bone trigger on F (70) and it worked fine, is force aim working? If not your key might be wrong http://cherrytree.at/misc/vk.htm

**Comment by JeeyM** [comment] 2019-05-06 11:12
Yes, force aim is working, both on ALT (18) and only force aim is working, but I will test again today

**Comment by AStupidRat** [comment] 2019-05-06 11:14
@JeeyM Are you using only body bone/head bone or both?

**Comment by JeeyM** [comment] 2019-05-06 11:15
Both

**Comment by AStupidRat** [comment] 2019-05-06 11:19
It probably wont fix your issue but I did find a problem where bone trigger won't activate if bone trigger head bone isn't enabled. It's the only possible solution I have atm, will come in an update either today or tomorrow.

**Comment by AStupidRat** [comment] 2019-05-07 07:04
@JeeyM I did find a couple issues with variables not resetting on each target call, let me know if the latest update (1.3) fixes bone trigger for you

**Comment by JeeyM** [comment] 2019-05-07 08:44
@AStupidRat I just tried, still the same problem, maybe it's because I play on fullscreen?

**Comment by AStupidRat** [comment] 2019-05-07 08:48
@JeeyM Fullscreen shouldnt be the problem, not sure what it could be for you if everything else is working

**Comment by JeeyM** [comment] 2019-05-07 08:50
The only problem is triggerbot, everything is working. On charlatano triggerbot is working for me

**Comment by AStupidRat** [comment] 2019-05-07 08:55
@JeeyM Since you're using fullscreen the menu is turned off correct?

**Comment by JeeyM** [comment] 2019-05-07 08:58
@AStupidRat even on Fullscreen Windowed or Borderless Mode I don't see any menu

**Comment by AStupidRat** [comment] 2019-05-07 08:59
@JeeyM If menu = true in general.kts when windowed or borderless F1 should open the menu

**Comment by JeeyM** [comment] 2019-05-07 09:00
Menu is enable. I press F1 and nothing happened

**Comment by AStupidRat** [comment] 2019-05-07 09:04
@JeeyM If you dont have box esp, skeleton esp, bomb timer or recoil crosshair enabled the menu wont launch either, maybe thats the case.

**Comment by JeeyM** [comment] 2019-05-07 09:05
I don't have any of this enabled

**Comment by AStupidRat** [comment] 2019-05-07 09:06
@JeeyM Setting one of those to true will enable the menu, is enable_bone_trigger = true in scripts.kts?

**Comment by JeeyM** [comment] 2019-05-07 09:09
@AStupidRat here are my BoneTrigger and Scripts settings:

BoneTrigger.kts
import rat.poison.settings.*

/**
 * The field of view (in degrees, 0 to 360) for the bone trigger.
 */
BONE_TRIGGER_FOV = 4

/**
 * Whether to trigger on head bone
 */
BONE_TRIGGER_HB = true

/**
 * Whether to trigger on body bone
 */
BONE_TRIGGER_BB = true

/**
 * Use aim when bone trigger activates, true by default
 */
AIM_ON_BONE_TRIGGER = true

/**
 * Enable using a key for bone trigger
 */
BONE_TRIGGER_ENABLE_KEY = true

/**
 * Key to use bone trigger for if bone trigger key is enabled; F by default
 */
BONE_TRIGGER_KEY = 18

/**
 * Default minimum time in milliseconds to fire shots when requirements met
 */
BONE_TRIGGER_SHOT_DELAY = 8


scripts.kts
import rat.poison.settings.*

/**
 * Enables the bunny hop script.
 *
 * To do this, type the following commands into the in-game developer console:
 * unbind "space"
 * bind "mwheelup" "+jump"
 * bind "mwheeldown" "+jump"
 */
ENABLE_BUNNY_HOP = true

/**
 * Enables the recoil control system (RCS) script.
 */
ENABLE_RCS = false

/**
 * Enables the recoil crosshair
 * This requires the overlay which only works when borderless fullscreen or windowed.
 */
ENABLE_RECOIL_CROSSHAIR = false

/**
 * Enables the extra sensory perception (ESP) script.
 */
ENABLE_ESP = true

/**
 * Enables the flat aim script.
 *
 * This script uses traditional flat linear-regression smoothing.
 */
ENABLE_FLAT_AIM = false

/**
 * Enables the path aim script.
 *
 * This script uses an advanced path generation smoothing.
 */
ENABLE_PATH_AIM = true

/**
 * Enables the bone trigger bot script.
 */
ENABLE_BONE_TRIGGER = true

/**
 * Enables the reduced flash script.
 */
ENABLE_REDUCED_FLASH = false

/**
 * Enables the bomb timer script.
 * This requires the overlay which only works when borderless fullscreen or windowed.
 */
ENABLE_BOMB_TIMER = false

**Comment by AStupidRat** [comment] 2019-05-07 09:10
@JeeyM Id recommend settings recoil crosshair = true to use the menu to test bone trigger, settings look like it should be working but clearly its not.

**Comment by JeeyM** [comment] 2019-05-07 09:14
My fault, I copied settings from 1.26, but it's the same for newest version

**Comment by AStupidRat** [comment] 2019-05-07 09:16
@JeeyM I've found the problem, will push an update in a couple minutes

**Comment by JeeyM** [comment] 2019-05-07 09:18
I also find the issue: now it's working with the menu, but without or on fullscreen it doesn't

**Comment by AStupidRat** [comment] 2019-05-07 09:21
@JeeyM Yes bone trigger is relying on the menu being initialized to function, fixing it so it works without the menu.

**Comment by JeeyM** [comment] 2019-05-07 09:23
@AStupidRat Yep, thanks

**Comment by AStupidRat** [comment] 2019-05-07 09:25
@JeeyM Just pushed the update, lmk how it goes

**Comment by JeeyM** [comment] 2019-05-07 09:34
@AStupidRat It's working now, thanks for help!

**Closed** 2019-05-07 09:35 UTC
